service: auth-server

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  timeout: 60 # optional, in seconds, default is 6
  environment:
    CLIENT_ID: ${file(config.json):client_id}
    CLIENT_SECRET: ${file(config.json):client_secret}
    PROJECT_ID: ${file(config.json):project_id}
    CALENDAR_ID: ${file(config.json):CALENDAR_ID}

functions:
  getAuthURL:
    handler: handler.getAuthURL
    events:
      - http:
          path: api/get-auth-url
          method: get
  getAccessToken:
    handler: handler.getAccessToken
    events:
      - http:
          path: api/token/{code}
          method: get 
